# Generated by Django 3.2.9 on 2022-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoName', models.CharField(max_length=30)),
                ('cryptoQuantity', models.IntegerField(max_length=10)),
                ('quantityDollars', models.IntegerField(max_length=10)),
            ],
        ),
    ]
