# Generated by Django 3.2.9 on 2022-03-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='cryptoQuantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='quantityDollars',
            field=models.FloatField(),
        ),
    ]
