# Generated by Django 3.2.9 on 2022-04-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyprice',
            options={'ordering': ['crypto', 'time_created', 'day_created']},
        ),
    ]
