# Generated by Django 3.2.9 on 2022-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20220324_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='cryptoName',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='cryptoQuantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
