# Generated by Django 3.2.9 on 2022-04-25 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_buyprice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyprice',
            options={'ordering': ['cryptoName', 'time_created', 'day_created']},
        ),
        migrations.RemoveField(
            model_name='buyprice',
            name='crypto',
        ),
        migrations.AddField(
            model_name='buyprice',
            name='cryptoName',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
