# Generated by Django 3.2.9 on 2022-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20220324_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollars', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CryptoCurrency',
            new_name='CryptoWallet',
        ),
    ]
