# Generated by Django 3.2.9 on 2022-04-06 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0004_auto_20220324_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashWallet',
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
