# Generated by Django 3.2.9 on 2022-06-16 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0005_walletid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendReceive_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_created', models.DateField()),
                ('time_created', models.TimeField()),
                ('type', models.CharField(max_length=15)),
                ('quantity', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day_created', '-time_created'],
            },
        ),
        migrations.CreateModel(
            name='DepositWithdraw_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_created', models.DateField()),
                ('time_created', models.TimeField()),
                ('type', models.CharField(max_length=15)),
                ('quantity', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day_created', '-time_created'],
            },
        ),
    ]
