# Generated by Django 3.2.9 on 2022-06-16 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_depositwithdraw_transaction_sendreceive_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendreceive_transaction',
            name='cryptoName',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
