# Generated by Django 3.2.9 on 2022-04-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='cryptoName',
            field=models.CharField(max_length=30),
        ),
    ]
