# Generated by Django 3.2.9 on 2022-04-11 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0007_alter_cryptowallet_cryptoname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=30)),
                ('coin', models.CharField(max_length=30)),
                ('quantityCrypto', models.FloatField()),
                ('quantityDollars', models.FloatField()),
                ('balance_after', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
