# Generated by Django 3.2.9 on 2022-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_auto_20220411_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcaction',
            name='day_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transcaction',
            name='time_created',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
