# Generated by Django 3.2.9 on 2022-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_auto_20220411_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcaction',
            name='day_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transcaction',
            name='time_created',
            field=models.TimeField(),
        ),
    ]
