# Generated by Django 3.2.9 on 2022-04-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0012_rename_transcaction_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['day_created']},
        ),
    ]
