# Generated by Django 3.2.9 on 2022-04-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0014_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-day_created', '-time_created']},
        ),
    ]
