# Generated by Django 3.2.9 on 2022-04-22 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0015_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('crypto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptowallet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
