# Generated by Django 3.2.9 on 2022-04-22 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0016_buyprices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyPrices',
            new_name='BuyPrice',
        ),
    ]
